# Generated by Django 3.1.5 on 2021-08-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_auto_20210824_0056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'country', 'publisher')},
        ),
    ]
