# Generated by Django 3.1.7 on 2021-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField(verbose_name='员工编号')),
                ('salary', models.IntegerField(verbose_name='薪资')),
                ('from_date', models.DateField(verbose_name='from_date')),
                ('to_date', models.DateField(verbose_name='to_date')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salaries',
            constraint=models.UniqueConstraint(fields=('emp_no', 'from_date'), name='sql7_uc_emp_no_from_date'),
        ),
    ]
