# Generated by Django 3.1.5 on 2021-09-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoonefield', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
