# Generated by Django 3.1.7 on 2021-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_horizontal_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
    ]
