# Generated by Django 3.1.7 on 2021-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('emp_no', models.IntegerField(max_length=11, primary_key=True, serialize=False, verbose_name='员工')),
                ('birth_date', models.DateField(verbose_name='生日日期')),
                ('first_name', models.CharField(max_length=14, verbose_name='姓氏')),
                ('last_name', models.CharField(max_length=16, verbose_name='名字')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
            ],
        ),
    ]
