# Generated by Django 3.1.7 on 2021-04-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefetch_related_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championed_by', to='prefetch_related_.pizza')),
                ('pizzas', models.ManyToManyField(related_name='restaurants', to='prefetch_related_.Pizza')),
            ],
        ),
    ]
