# Generated by Django 3.1.7 on 2021-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.CharField(max_length=200, verbose_name='文章内容')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('tags', models.CharField(max_length=200, verbose_name='文章标签')),
                ('date_joined', models.CharField(max_length=200, verbose_name='文章创建时间')),
            ],
        ),
    ]
