# Generated by Django 3.1.7 on 2021-03-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='date_joined',
            field=models.DateTimeField(verbose_name='文章创建时间'),
        ),
    ]
