# Generated by Django 3.1.7 on 2021-03-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('expiration_date', models.IntegerField(help_text='按天', verbose_name='有效期')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='商品录入时间')),
            ],
        ),
    ]
