# Generated by Django 3.1.7 on 2021-04-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplerelate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),

        migrations.RunSQL("insert into simplerelate_tag (`id`, `name`) values ('1', 'os module');"),

        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simplerelate.tag'),
            preserve_default=False,
        ),
    ]
