# Generated by Django 3.1.7 on 2021-04-01 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delete_', '0002_product_date_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='商品修改时间'),
        ),
    ]
