# Generated by Django 3.1.7 on 2021-04-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delete_', '0003_auto_20210401_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_changed',
            field=models.DateTimeField(null=True, verbose_name='商品修改时间'),
        ),
    ]
