# Generated by Django 3.1.7 on 2021-04-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delete_', '0004_auto_20210401_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_changed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='商品修改时间'),
        ),
    ]
