# Generated by Django 3.1.7 on 2021-04-01 05:50
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delete_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_changed',
            field=models.DateTimeField(default=timezone.now, verbose_name='商品修改时间'),
            preserve_default=False,
        ),
    ]
